server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 ipv6=off;

    root /usr/share/nginx/html;
    index index.html;

    location /auth-api/ {
        set $auth_upstream helpdesk-utp-auth:8080;
        rewrite ^/auth-api/(.*)$ /$1 break;
        proxy_pass http://$auth_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /user-api/ {
        set $user_upstream helpdesk-utp-user:8080;
        rewrite ^/user-api/(.*)$ /$1 break;
        proxy_pass http://$user_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /support-api/ {
        set $support_upstream helpdesk-utp-support:8080;
        rewrite ^/support-api/(.*)$ /$1 break;
        proxy_pass http://$support_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin-api/ {
        set $admin_upstream helpdesk-utp-admin:8080;
        rewrite ^/admin-api/(.*)$ /$1 break;
        proxy_pass http://$admin_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
