@helpdesk_utp_auth_HostAddress = http://localhost:5000

POST {{helpdesk_utp_auth_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "user1",
  "password": "testpassword"
}

###

POST {{helpdesk_utp_auth_HostAddress}}/auth/logout
